<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<title>Jun Wang — Designer. Developer.</title><meta name="keywords" content=" Designer, Developer, Webdesign, Screendesign, HTML, CSS, WordPress, Portfolio, Sass">
	<meta name="description" content="This is the portfolio, blog and digital playground from Jun Wang.">
	<meta name="author" content="Jun Wang - http://www.webdesignerjun.com">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0,maximum-scale=1.0">
	<link rel="shortcut icon" href="/img/logo.png" type="image/x-icon" />
	<script type="text/javascript" src="/js/lib/jquery.min.js"></script>
	<link rel="stylesheet" href="css/lib/tinyeditor.css" />
	<script type="text/javascript" src="/js/lib/tinyeditor.js"></script>
	<link rel="stylesheet" href="css/lib/flat-ui.css" type="text/css" media="screen">
	<link rel="stylesheet" href="css/mainPage/style.css" type="text/css" media="screen">
	<link rel="stylesheet" href="css/addArticle/style.css" type="text/css" media="screen">
	<script>
		window.userHash = "<?php echo $this->userHash?>";
	</script>
</head>
<body>

	<!-- start: Loader -->
	<div class="loadingWrapper" style="top: 100%; display: none; opacity: 0.9;">
	  <div class="loading">
	    <h2>Jun<br>Wang<br></h2>
	    <h3>loading...</h3>
	  </div>
	</div>
	<!-- start: websiteWrapper -->
	<section class="websiteWrapper">

	  <!-- start: pageHeader -->
	  <header class="websiteHeader ">
	    <nav class="websiteNav">
	      <h1>
	        <a href="/">Jun Wang</a>
	      </h1>
	      <ul class="prim">
	        <li><a href="/">Work</a></li>
	        <li><a href="/">Blog</a></li>
	        <li><a href="/">About</a></li>
	      </ul>
	      <ul class="sec">
	        <li>
	        	<a href="mailto:junwang6302@gmail.com" class="js_showContact">
	        		<img class="mail" src="img/icons/svg/mail.svg" alt="Mail">
	        	</a>
	        </li>
	        <li><a href="/" class="js_showSearch">
	        	<!-- <i class="icon icon-search fui-search"></i> -->
	        	<span class="fui-search"></span>
	        </a></li>
	      </ul>
	      <ul class="mobile">
	        <li><a href="/#mobileNav" class="js_showMobileNav"><i class="icon"><span class="fui-list"></span></i></a></li>
	      </ul>
	    </nav>
	  </header>

	  <div class="mobileNavWrapper">
	    <nav class="navi">
	      <ul>
	        <li><a href="/">Work</a></li>
	        <li><a href="/">Blog</a></li>
	        <li><a href="/">About</a></li>
	        <li><a href="mailto:junwang6302@gmail.com" class="js_showContact"><i class="icon"><img class="mail" src="img/icons/svg/mail.svg" alt="Mail"></i></a></li>
	        <li><a href="/" class="js_showSearch js_hideMobileNav"><i class="icon"><span class="fui-search"></span></i></a></li>
	      </ul>
	    </nav>
	  </div>


	  <section class="articleArchiv">

	  	<div class="input-container">
	  		
	  		<div class="subject-container">
	  			<input type="text" placeholder="Please type subject here.." class="form-control subject-input" id="subject-input"/>
	  		</div>

	  		<textarea id="input" style="width:400px; height:200px"></textarea>

	  	</div>
	  	<div class="save-btn-container">
	  		<button class="btn save-btn btn-primary btn-wide">
 				Save
			</button>
	  	</duv>	
	   <!--  <ul class="sameHeight">

          <li style="height: 474px;">

	        <a href="/" rel="bookmark" title=" Ray-Ban Polarized Tour 2014 — #iampolarized  #polarizedtour2014">
	          <span class="date">30, June 2014</span>
	          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
	          <div class="readMore">Read Article<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	          <li style="height: 474px;">
	        <a href="/" rel="bookmark" title=" CSS Media Queries: Das Problem mit fixen Breakpoints">
	          <span class="date">19, May 2014</span>
	          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
	          <div class="readMore">Read Article<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	          <li style="height: 474px;">
	        <a href="/" rel="bookmark" title=" #changeCGN — Minirampe gegen hässliches Köln!">
	          <span class="date">18, May 2014</span>
	          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
	          <div class="readMore">Read Article<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	          <li style="height: 434px;">
	        <a href="/" title=" dribbble invites zu vergeben!">
	          <span class="date">12, May 2014</span>
	          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
	          <div class="readMore">Read Article<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	          <li style="height: 434px;">
	        <a href="/" title=" AWWWARDS — Honorable Mention">
	          <span class="date">12, May 2014</span>
	          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
	          <div class="readMore">Read Article<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	          <li style="height: 434px;">
	        <a href="/" title=" Peak! Vote for me on AWWWARDS">
	          <span class="date">08, May 2014</span>
	          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
	          <div class="readMore">Read Article<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
        </ul>
	    <a class="getMoreButton" href="/">More Articles</a> -->
	  </section>

	<section class="myWork" id="work">
	  <a href="/" class="scrollDown">
	    <i class="icon"><span class="fui-triangle-down down-arrow"></span></i>See my work
	  </a>
		
	  <section class="moreWork">
	    <ul class="sameHeight">
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>AWS</h2>
	          <figure>
	            <!-- <img class="preview" src="/img/amazon-aws.png" alt="AWS">
	            <img class="helper" src="/img/amazon-aws.png" alt="helper"> -->
	            <div class="aws">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>PHP ZEND</h2>
	          <figure>
	            <div class="zend">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>HTML 5</h2>
	          <figure>
	            <div class="html5">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>Javascript</h2>
	          <figure>
	            <div class="js">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	          </ul>
	    <a class="getMoreButton" href="/">See all my Work</a>
	  </section>

	</section>
	  <footer class="websiteFooter">
	    <section class="footerContent">
	      <div class="shortInfo">
	        © 2014-2015 Jun Wang<br>
	      </div>
	      <ul class="socialIcons">
	        <li><a href="/"><i class="icon icon-tumblr"></i></a></li>
	        <li><a href="/"><i class="icon icon-dribbble"></i></a></li>
	        <li><a href="/"><i class="icon icon-twitter"></i></a></li>
	        <li><a href="/"><i class="icon icon-instagram"></i></a></li>
	      </ul>
	    </section>
	  </footer>
	</section>

	<!-- start: pageHeader Sticky -->
	<header class="websiteHeaderSticky">
	  <nav class="websiteNav">
	    <h1>
	      <a href="/">Jun Wang</a>
	    </h1>
	    <ul class="prim">
	      <li><a href="/">Work</a></li>
	      <li><a href="/">Blog</a></li>
	      <li><a href="/">About</a></li>
	    </ul>
	    <ul class="sec">
	      <li>
	      	<a href="mailto:junwang6302@gmail.com" class="js_showContact">
	      		<img class="mail" src="img/icons/svg/mail.svg" alt="Mail">
	      	</a>
	      </li>
	      <li>
	      	<a href="/" class="js_showSearch">
	      		<span class="fui-search"></span>
	      	</a>
	      </li>
	    </ul>
	    <ul class="mobile">
	      <li><a href="/#mobileNav" class="js_showMobileNav"><i class="icon"><span class="fui-list"></span></i></a></li>
	    </ul>
	  </nav>
	</header>
	<script type="text/javascript" src="js/mainPage/imagelightbox.min.js"></script>
	<script type="text/javascript" src="js/mainPage/scripts-ck.js"></script>
	<script type="text/javascript" src="js/addArticle/addArticle.js"></script>

	<script type="text/javascript">
	window.teWidth = 0.8 * $('.input-container').width();
	var textEditor = new TINY.editor.edit('editor',{
		id:'input',
		width:teWidth,
		height:175,
		cssclass:'te',
		controlclass:'tecontrol',
		rowclass:'teheader',
		dividerclass:'tedivider',
		controls:['bold','italic','underline','strikethrough','|','subscript','superscript','|',
				  'orderedlist','unorderedlist','|','outdent','indent','|','leftalign',
				  'centeralign','rightalign','blockjustify','|','unformat','|','undo','redo','n',
				  'font','size','style','|','image','hr','link','unlink','|','cut','copy','paste','print'],
		footer:true,
		fonts:['Verdana','Arial','Georgia','Trebuchet MS'],
		xhtml:true,
		cssfile:'css/lib/tinyeditor.css',
		bodyid:'editor',
		footerclass:'tefooter',
		toggle:{text:'source',activetext:'wysiwyg',cssclass:'toggle'},
		resize:{cssclass:'resize'}
	});
	</script>
</body>
</html>