<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<title>Jun Wang — Designer. Developer.</title><meta name="keywords" content=" Designer, Developer, Webdesign, Screendesign, HTML, CSS, WordPress, Portfolio, Sass">
	<meta name="description" content="This is the portfolio, blog and digital playground from Jun Wang.">
	<meta name="author" content="Jun Wang - http://www.webdesignerjun.com">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0,maximum-scale=1.0">
	<link rel="shortcut icon" href="/img/logo.png" type="image/x-icon" />
	<script type="text/javascript" src="/js/lib/jquery.min.js"></script>
	<script type="text/javascript" src="/js/lib/angular.js"></script>
	<link rel="stylesheet" href="css/lib/flat-ui.css" type="text/css" media="screen">
	<link rel="stylesheet" href="css/mainPage/style.css" type="text/css" media="screen">
	<link rel="stylesheet" href="css/article/style.css" type="text/css" media="screen">
	<script>
		window.article_id = "<?php echo $this->article_id?>";
	    window.userHash = "<?php echo $this->userHash?>";
	</script>
</head>
<body ng-app="articleApp">

	<!-- start: Loader -->
	<div class="loadingWrapper" style="top: 100%; display: none; opacity: 0.9;">
	  <div class="loading">
	    <h2>Jun<br>Wang<br></h2>
	    <h3>loading...</h3>
	  </div>
	</div>
	<!-- start: websiteWrapper -->
	<section class="websiteWrapper">

	  <!-- start: pageHeader -->
	  <header class="websiteHeader ">
	    <nav class="websiteNav">
	      <h1>
	        <a href="/">Jun Wang</a>
	      </h1>
	      <ul class="prim">
	        <li><a href="/">Work</a></li>
	        <li><a href="/">Blog</a></li>
	        <li><a href="/">About</a></li>
	      </ul>
	      <ul class="sec">
	        <li>
	        	<a href="mailto:junwang6302@gmail.com" class="js_showContact">
	        		<img class="mail" src="img/icons/svg/mail.svg" alt="Mail">
	        	</a>
	        </li>
	        <li><a href="/" class="js_showSearch">
	        	<!-- <i class="icon icon-search fui-search"></i> -->
	        	<span class="fui-search"></span>
	        </a></li>
	      </ul>
	      <ul class="mobile">
	        <li><a href="/#mobileNav" class="js_showMobileNav"><i class="icon"><span class="fui-list"></span></i></a></li>
	      </ul>
	    </nav>
	  </header>

	  <div class="mobileNavWrapper">
	    <nav class="navi">
	      <ul>
	        <li><a href="/">Work</a></li>
	        <li><a href="/">Blog</a></li>
	        <li><a href="/">About</a></li>
	        <li><a href="mailto:junwang6302@gmail.com" class="js_showContact"><i class="icon"><img class="mail" src="img/icons/svg/mail.svg" alt="Mail"></i></a></li>
	        <li><a href="/" class="js_showSearch js_hideMobileNav"><i class="icon"><span class="fui-search"></span></i></a></li>
	      </ul>
	    </nav>
	  </div>


	  <section class="articleArchiv">

	  	<div class="articlelist-container" ng-controller="mainCtrl">
	  		
	  		<!-- <div class="article-container" ng-repeat="article in articles"> -->
	  		<div class="article-container" >

	  			<div class="article">

	  				<section class="pageHeadline">
						<h2>
							{{article.subject}}			  			
							<span class="date"><span>{{article.date}}</span></span>
						</h2>
					</section>

	  				<!-- <div class="subject">
	  					{{article.subject}}
	  				</div>

	  				<div class="date">
	  					{{article.date}}
	  				</div> -->
		  			<section class="blogDetailWrapper">
					  	
					  	<article class="articleWrapper">
					  		
					  		<div class="content">

			  				</div>	

							<!-- <p class="postStats">Gelesen: 1421 — Heute: 4 </p> -->
					  		
					    </article>

						<!-- <div class="pagination">
							<div class="alignleft"><a href="http://davidhellmann.com/tipps-und-tricks/content-bilder-ein-max-height-kann-oft-helfen-2534/" rel="prev"><i class="icon lessMargin icon-arrow-left"></i> Older</a></div>
							<div class="alignright"><a href="http://davidhellmann.com/blogging/joining-austria-joining-salzburg-joining-red-bull-creative-hello-2544/" rel="next">Newer <i class="icon lessMargin icon-arrow-right"></i></a></div>
						</div> -->

					</section>
	  				
	  				<!-- <div id="{{article.id}}">
	  					
	  				</div>	 -->
	  			</div>	
	  			<br/>	
	  		</div>

	  	</div>

	  	<!-- Here can be a more btn / scroll action - J
	  	<div class="save-btn-container">
	  		<button class="btn save-btn btn-primary btn-wide">
 				Save
			</button>
	  	</duv>	 -->
	
	  </section>

	<section class="myWork" id="work">
	  <a href="/" class="scrollDown">
	    <i class="icon"><span class="fui-triangle-down down-arrow"></span></i>See my work
	  </a>
		
	  <section class="moreWork">
	    <ul class="sameHeight">
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>AWS</h2>
	          <figure>
	            <!-- <img class="preview" src="/img/amazon-aws.png" alt="AWS">
	            <img class="helper" src="/img/amazon-aws.png" alt="helper"> -->
	            <div class="aws">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>PHP ZEND</h2>
	          <figure>
	            <div class="zend">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>HTML 5</h2>
	          <figure>
	            <div class="html5">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>Javascript</h2>
	          <figure>
	            <div class="js">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	          </ul>
	    <a class="getMoreButton" href="/">See all my Work</a>
	  </section>

	</section>
	  <footer class="websiteFooter">
	    <section class="footerContent">
	      <div class="shortInfo">
	        © 2014-2015 Jun Wang<br>
	      </div>
	      <ul class="socialIcons">
	        <li><a href="/"><i class="icon icon-tumblr"></i></a></li>
	        <li><a href="/"><i class="icon icon-dribbble"></i></a></li>
	        <li><a href="/"><i class="icon icon-twitter"></i></a></li>
	        <li><a href="/"><i class="icon icon-instagram"></i></a></li>
	      </ul>
	    </section>
	  </footer>
	</section>

	<!-- start: pageHeader Sticky -->
	<header class="websiteHeaderSticky">
	  <nav class="websiteNav">
	    <h1>
	      <a href="/">Jun Wang</a>
	    </h1>
	    <ul class="prim">
	      <li><a href="/">Work</a></li>
	      <li><a href="/">Blog</a></li>
	      <li><a href="/">About</a></li>
	    </ul>
	    <ul class="sec">
	      <li>
	      	<a href="mailto:junwang6302@gmail.com" class="js_showContact">
	      		<img class="mail" src="img/icons/svg/mail.svg" alt="Mail">
	      	</a>
	      </li>
	      <li>
	      	<a href="/" class="js_showSearch">
	      		<span class="fui-search"></span>
	      	</a>
	      </li>
	    </ul>
	    <ul class="mobile">
	      <li><a href="/#mobileNav" class="js_showMobileNav"><i class="icon"><span class="fui-list"></span></i></a></li>
	    </ul>
	  </nav>
	</header>
	<script type="text/javascript" src="js/mainPage/imagelightbox.min.js"></script>
	<script type="text/javascript" src="js/mainPage/scripts-ck.js"></script>
	<script type="text/javascript" src="js/article/article.js"></script>

</body>
</html>