<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<title>Jun Wang — Designer. Developer.</title><meta name="keywords" content=" Designer, Developer, Webdesign, Screendesign, HTML, CSS, WordPress, Portfolio, Sass">
	<meta name="description" content="This is the portfolio, blog and digital playground from Jun Wang.">
	<meta name="author" content="Jun Wang - http://www.webdesignerjun.com">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0,maximum-scale=1.0">
	<link rel="shortcut icon" href="/img/logo.png" type="image/x-icon" />
	<script type="text/javascript" src="/js/lib/jquery.min.js"></script>
	<script type="text/javascript" src="/js/lib/angular.js"></script>
	<link rel="stylesheet" href="css/lib/flat-ui.css" type="text/css" media="screen">
	<link rel="stylesheet" href="css/mainPage/style.css" type="text/css" media="screen">
	<link rel="stylesheet" href="css/articleList/style.css" type="text/css" media="screen">
</head>
<body ng-app="articleListApp">

	<!-- start: Loader -->
	<div class="loadingWrapper" style="top: 100%; display: none; opacity: 0.9;">
	  <div class="loading">
	    <h2>Jun<br>Wang<br></h2>
	    <h3>loading...</h3>
	  </div>
	</div>
	<!-- start: websiteWrapper -->
	<section class="websiteWrapper">

	  <!-- start: pageHeader -->
	  <header class="websiteHeader ">
	    <nav class="websiteNav">
	      <h1>
	        <a href="/">Jun Wang</a>
	      </h1>
	      <ul class="prim">
	        <li><a href="/">Work</a></li>
	        <li><a href="/">Blog</a></li>
	        <li><a href="/">About</a></li>
	      </ul>
	      <ul class="sec">
	        <li>
	        	<a href="mailto:junwang6302@gmail.com" class="js_showContact">
	        		<img class="mail" src="img/icons/svg/mail.svg" alt="Mail">
	        	</a>
	        </li>
	        <li><a href="/" class="js_showSearch">
	        	<!-- <i class="icon icon-search fui-search"></i> -->
	        	<span class="fui-search"></span>
	        </a></li>
	      </ul>
	      <ul class="mobile">
	        <li><a href="/#mobileNav" class="js_showMobileNav"><i class="icon"><span class="fui-list"></span></i></a></li>
	      </ul>
	    </nav>
	  </header>

	  <div class="mobileNavWrapper">
	    <nav class="navi">
	      <ul>
	        <li><a href="/">Work</a></li>
	        <li><a href="/">Blog</a></li>
	        <li><a href="/">About</a></li>
	        <li><a href="mailto:junwang6302@gmail.com" class="js_showContact"><i class="icon"><img class="mail" src="img/icons/svg/mail.svg" alt="Mail"></i></a></li>
	        <li><a href="/" class="js_showSearch js_hideMobileNav"><i class="icon"><span class="fui-search"></span></i></a></li>
	      </ul>
	    </nav>
	  </div>


	  <section class="articleArchiv">

	  	<div class="articlelist-container" ng-controller="mainCtrl">
	  		
	  		<div class="article-container" ng-repeat="article in articles">

	  			<div class="article">
	  				<a href="/article?id={{article.id}}">
		  				<div class="subject">
		  					{{article.subject}}
		  				</div>
		  				<div class="date">
		  					{{article.date}}
		  				</div>
		  			</a>
	  				<!-- <div class="content">
	  						{{article.content}}
	  				</div>	 -->
	  				<!-- <div id="{{article.id}}">
	  					
	  				</div>	 -->
	  			</div>	
	  			<br/>	
	  		</div>

	  	</div>

	  	<!-- Here can be a more btn / scroll action - J
	  	<div class="save-btn-container">
	  		<button class="btn save-btn btn-primary btn-wide">
 				Save
			</button>
	  	</duv>	 -->
	
	  </section>

	<section class="myWork" id="work">
	  <a href="/" class="scrollDown">
	    <i class="icon"><span class="fui-triangle-down down-arrow"></span></i>See my work
	  </a>
		
	  <section class="moreWork">
	    <ul class="sameHeight">
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>AWS</h2>
	          <figure>
	            <!-- <img class="preview" src="/img/amazon-aws.png" alt="AWS">
	            <img class="helper" src="/img/amazon-aws.png" alt="helper"> -->
	            <div class="aws">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>PHP ZEND</h2>
	          <figure>
	            <div class="zend">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>HTML 5</h2>
	          <figure>
	            <div class="html5">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	                   <li style="height: 502px;">
	        <a href="/">
	          <h2>Javascript</h2>
	          <figure>
	            <div class="js">
	            </div>
	          </figure>
	          <div class="readMore">View details<i class="icon"><span class="fui-arrow-right"></span></i></div>
	        </a>
	      </li>
	          </ul>
	    <a class="getMoreButton" href="/">See all my Work</a>
	  </section>

	</section>
	  <footer class="websiteFooter">
	    <section class="footerContent">
	      <div class="shortInfo">
	        © 2014-2015 Jun Wang<br>
	      </div>
	      <ul class="socialIcons">
	        <li><a href="/"><i class="icon icon-tumblr"></i></a></li>
	        <li><a href="/"><i class="icon icon-dribbble"></i></a></li>
	        <li><a href="/"><i class="icon icon-twitter"></i></a></li>
	        <li><a href="/"><i class="icon icon-instagram"></i></a></li>
	      </ul>
	    </section>
	  </footer>
	</section>

	<!-- start: pageHeader Sticky -->
	<header class="websiteHeaderSticky">
	  <nav class="websiteNav">
	    <h1>
	      <a href="/">Jun Wang</a>
	    </h1>
	    <ul class="prim">
	      <li><a href="/">Work</a></li>
	      <li><a href="/">Blog</a></li>
	      <li><a href="/">About</a></li>
	    </ul>
	    <ul class="sec">
	      <li>
	      	<a href="mailto:junwang6302@gmail.com" class="js_showContact">
	      		<img class="mail" src="img/icons/svg/mail.svg" alt="Mail">
	      	</a>
	      </li>
	      <li>
	      	<a href="/" class="js_showSearch">
	      		<span class="fui-search"></span>
	      	</a>
	      </li>
	    </ul>
	    <ul class="mobile">
	      <li><a href="/#mobileNav" class="js_showMobileNav"><i class="icon"><span class="fui-list"></span></i></a></li>
	    </ul>
	  </nav>
	</header>
	<script type="text/javascript" src="js/mainPage/imagelightbox.min.js"></script>
	<script type="text/javascript" src="js/mainPage/scripts-ck.js"></script>
	<script type="text/javascript" src="js/articleList/articleList.js"></script>

</body>
</html>