<!DOCTYPE html>
<!-- saved from url=(0025)http://davidhellmann.com/ -->
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
	<title>Jun Wang — Designer. Developer.</title><meta name="keywords" content=" Designer, Developer, Webdesign, Screendesign, HTML, CSS, WordPress, Portfolio, Sass">
  <meta name="description" content="This is the portfolio, blog and digital playground from Jun Wang.">
  <meta name="author" content="Jun Wang - http://www.webdesignerjun.com">

  <!-- <link rel="shortcut icon" href="http://davidhellmann.com/wordpress/wp-content/themes/flatman/assets/img/favicon.ico" type="image/x-icon"> -->
  <!-- <link rel="icon" href="http://davidhellmann.com/wordpress/wp-content/themes/flatman/assets/img/favicon.png" type="image/png"> -->
  <!-- <link rel="apple-touch-icon-precomposed" sizes="152x152" href="http://davidhellmann.com/wordpress/wp-content/themes/flatman/assets/img/favicon-152.png"> -->
  <!-- <link rel="apple-touch-icon-precomposed" sizes="120x120" href="http://davidhellmann.com/wordpress/wp-content/themes/flatman/assets/img/favicon-120.png"> -->
	<meta name="viewport" content="width=device-width, minimum-scale=1.0,maximum-scale=1.0">

	<link rel="stylesheet" href="css/mainPage/style.css" type="text/css" media="screen">
  <script type="text/javascript" src="/js/lib/jquery.min.js"></script>

</head>

<body id="top">
<!-- start: Loader -->
<div class="loadingWrapper" style="top: 100%; display: none; opacity: 0.9;">
  <div class="loading">
    <h2>Jun<br>Wang<br></h2>
    <h3>loading...</h3>
  </div>
</div>
<!-- start: websiteWrapper -->
<section class="websiteWrapper">

  <!-- start: pageHeader -->
  <header class="websiteHeader ">
    <nav class="websiteNav">
      <h1>
        <a href="/">Jun Wang</a>
      </h1>
      <ul class="prim">
        <li><a href="/">Work</a></li>
        <li><a href="/">Blog</a></li>
        <li><a href="/">About</a></li>
      </ul>
      <ul class="sec">
        <li><a href="mailto:junwang6302@gmail.com" class="js_showContact"><i class="icon icon-bubbles"></i></a></li>
        <li><a href="/" class="js_showSearch"><i class="icon icon-search"></i></a></li>
      </ul>
      <ul class="mobile">
        <li><a href="/" class="js_showMobileNav"><i class="icon icon-menu"></i></a></li>
      </ul>
    </nav>
  </header>

  <div class="mobileNavWrapper">
    <nav class="navi">
      <ul>
        <li><a href="/">Work</a></li>
        <li><a href="/">Blog</a></li>
        <li><a href="/">About</a></li>
        <li><a href="mailto:junwang6302@gmail.com" class="js_showContact"><i class="icon icon-bubbles"></i></a></li>
        <li><a href="/" class="js_showSearch js_hideMobileNav"><i class="icon icon-search"></i></a></li>
      </ul>
    </nav>
  </div>

  <section class="welcomeWrapper">
    <figure style="background-image: url(/img/cute_profile.png);">
      <figcaption>
        <h2><span>Designer<br>Developer<br></span></h2>
        <h3>Hi, I'm Jun Wang, an Ireland based web developer.<br>Who want to make the world slightly better....</h3>
      </figcaption>
    </figure>
    <a href="/" class="scrollDown" id="article">
      <i class="icon icon-arrow-bottom"></i>Read my Articles
    </a>
  </section>


  <section class="articleArchiv">
    <ul class="sameHeight">
          <li style="height: 474px;">
        <a href="/" rel="bookmark" title=" Ray-Ban Polarized Tour 2014 — #iampolarized  #polarizedtour2014">
          <span class="date">30, June 2014</span>
          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          <li style="height: 474px;">
        <a href="/" rel="bookmark" title=" CSS Media Queries: Das Problem mit fixen Breakpoints">
          <span class="date">19, May 2014</span>
          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          <li style="height: 474px;">
        <a href="/" rel="bookmark" title=" #changeCGN — Minirampe gegen hässliches Köln!">
          <span class="date">18, May 2014</span>
          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          <li style="height: 434px;">
        <a href="/" title=" dribbble invites zu vergeben!">
          <span class="date">12, May 2014</span>
          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          <li style="height: 434px;">
        <a href="/" title=" AWWWARDS — Honorable Mention">
          <span class="date">12, May 2014</span>
          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          <li style="height: 434px;">
        <a href="/" title=" Peak! Vote for me on AWWWARDS">
          <span class="date">08, May 2014</span>
          <h2>xxxx xxxxx xxxx xxxx xxxxx</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
            </ul>
    <a class="getMoreButton" href="http://davidhellmann.com/blog">More Articles</a>
  </section>

<section class="myWork" id="work">
  <a href="/" class="scrollDown">
    <i class="icon icon-arrow-bottom"></i>See my work
  </a>

  
    <section class="latestWorkWrapper">
    <div class="latestWork">
      <div class="ipad">
        <div class="homeButton"><span></span></div>
        <div class="camera"></div>
        <figure>
          <a class="link" href="/">
  		      <!-- <img class="preview" src="/img/tweekaboo_0.jpg" alt="Tweekaboo"> -->
            <img class="helper" src="/img/tweekaboo_0.jpg" alt="helper">
  		    </a>
        </figure>
      </div>
      <div class="content">
        <h2>TWeekaboo</h2>
        <p>
          An online Journal / Diary App for modern parents, Tweekaboo makes it easy to record your pregnancy and baby's firsts and milestones. Share photos & videos ...      </p>
        <div class="colors">
                    	        		<span class="colorField" style="background: #ebae0c"></span>
          	        		<span class="colorField" style="background: #f2f2f2"></span>
          	        		<span class="colorField" style="background: #342514"></span>
          	        		<span class="colorField" style="background: #90a1ae"></span>
          	        		<span class="colorField" style="background: #ffffff"></span>
          	        		<span class="colorField" style="background: #333333"></span>
          	                  </div>

        <ul class="range">
          <li>AWS </li><li>PHP Backend Developement</li><li>Frontend Development</li>        </ul>
        <a class="getMoreButton" href="http://davidhellmann.com/work/home-on-earth/" title="Home on Earth">View details</a>
      </div>
    </div>
  </section>
	
  <section class="moreWork">
    <ul class="sameHeight">
                   <li style="height: 502px;">
        <a href="/">
          <h2>AWS</h2>
          <figure>
            <!-- <img class="preview" src="/img/amazon-aws.png" alt="AWS">
            <img class="helper" src="/img/amazon-aws.png" alt="helper"> -->
            <div class="aws">
            </div>
          </figure>
          <div class="readMore">View details<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
                   <li style="height: 502px;">
        <a href="http://davidhellmann.com/work/makebetterwebsites/">
          <h2>PHP ZEND</h2>
          <figure>
            <div class="zend">
            </div>
          </figure>
          <div class="readMore">View details<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
                   <li style="height: 502px;">
        <a href="http://davidhellmann.com/work/betterdoc/">
          <h2>HTML 5</h2>
          <figure>
            <div class="html5">
            </div>
          </figure>
          <div class="readMore">View details<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
                   <li style="height: 502px;">
        <a href="http://davidhellmann.com/work/deutsches-obst-und-gemuese/">
          <h2>Javascript</h2>
          <figure>
            <div class="js">
            </div>
          </figure>
          <div class="readMore">View details<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          </ul>
    <a class="getMoreButton" href="http://davidhellmann.com/work">See all my Work</a>
  </section>

</section>
  <footer class="websiteFooter">
    <section class="footerContent">
      <div class="shortInfo">
        © 2014-2015 Jun Wang<br>
      </div>
      <ul class="socialIcons">
        <li><a href="/"><i class="icon icon-tumblr"></i></a></li>
        <li><a href="/"><i class="icon icon-dribbble"></i></a></li>
        <li><a href="/"><i class="icon icon-twitter"></i></a></li>
        <li><a href="/"><i class="icon icon-instagram"></i></a></li>
      </ul>
    </section>
  </footer>
</section>

<!-- start: pageHeader Sticky -->
<header class="websiteHeaderSticky">
  <nav class="websiteNav">
    <h1>
      <a href="/">Jun Wang</a>
    </h1>
    <ul class="prim">
      <li><a href="http://davidhellmann.com/work">Work</a></li>
      <li><a href="http://davidhellmann.com/blog">Blog</a></li>
      <li><a href="http://davidhellmann.com/about">About</a></li>
    </ul>
    <ul class="sec">
      <li><a href="mailto:junwang6302@gmail.com" class="js_showContact"><i class="icon icon-bubbles"></i></a></li>
      <li><a href="/" class="js_showSearch"><i class="icon icon-search"></i></a></li>
    </ul>
    <ul class="mobile">
      <li><a href="/" class="js_showMobileNav"><i class="icon icon-menu"></i></a></li>
    </ul>
  </nav>
</header>
<script type="text/javascript" src="js/mainPage/scripts-ck.js"></script>

</body></html>