<!DOCTYPE html>
<!-- saved from url=(0025)http://davidhellmann.com/ -->
<html class="wf-fftisawebpro-n4-active wf-museosans-n1-active wf-museosans-n5-active wf-museosans-n7-active wf-museosans-n9-active wf-fftisawebpro-i4-active wf-fftisawebpro-i7-active wf-fftisawebpro-n7-active wf-museosans-n3-active wf-active"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
	<title>Jun Wang — Designer. Developer.</title><meta name="keywords" content=" Designer, Developer, Webdesign, Screendesign, HTML, CSS, WordPress, Portfolio, Sass">
<meta name="robots" content="index, follow">
<meta name="description" content="This is the portfolio, blog and digital playground from Jun Wang.">
<meta name="author" content="Jun Wang - http://www.webdesignerjun.com">

<!-- <link rel="shortcut icon" href="http://davidhellmann.com/wordpress/wp-content/themes/flatman/assets/img/favicon.ico" type="image/x-icon"> -->
<!-- <link rel="icon" href="http://davidhellmann.com/wordpress/wp-content/themes/flatman/assets/img/favicon.png" type="image/png"> -->
<!-- <link rel="apple-touch-icon-precomposed" sizes="152x152" href="http://davidhellmann.com/wordpress/wp-content/themes/flatman/assets/img/favicon-152.png"> -->
<!-- <link rel="apple-touch-icon-precomposed" sizes="120x120" href="http://davidhellmann.com/wordpress/wp-content/themes/flatman/assets/img/favicon-120.png"> -->
	<meta name="viewport" content="width=device-width, minimum-scale=1.0,maximum-scale=1.0">
	<!-- <meta name="bitly-verification" content="d00ca51b9494"> -->
	<!-- Place this tag in the <head> of your document-->
	
	<script src="/js/mainPage/cb=gapi.loaded_0" async=""></script>
  <script type="text/javascript" src="js/mainPage/ymu2lxh.js"></script>
  <style type="text/css">.tk-ff-tisa-web-pro{font-family:"ff-tisa-web-pro",serif;}.tk-museo-sans{font-family:"museo-sans",sans-serif;}</style>

	<link rel="alternate" type="application/rss+xml" title="David Hellmann - RSS Feed" href="http://davidhellmann.com/feed/">
	<link rel="pingback" href="http://davidhellmann.com/wordpress/xmlrpc.php">
	<link rel="stylesheet" href="css/mainPage/style.css" type="text/css" media="screen">
  <script type="text/javascript" src="/js/lib/jquery.min.js"></script>
  <script type="text/javascript" src="/js/mainPage/imagelightbox.min.js"></script>
	<link rel="alternate" type="application/rss+xml" title="David Hellmann — Designer. Developer. Cyclist. — @davidhellmann » Start Comments Feed" href="http://davidhellmann.com/start/feed/">
<link rel="stylesheet" id="wp-syntax-css-css" href="/css/maibPage/wp-syntax.css" type="text/css" media="all">
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://davidhellmann.com/wordpress/xmlrpc.php?rsd">
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://davidhellmann.com/wordpress/wp-includes/wlwmanifest.xml"> 
<link rel="next" title="Blog" href="http://davidhellmann.com/blog/">
<meta name="generator" content="WordPress 3.9.1">
<link rel="canonical" href="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/David Hellmann — Designer. Developer. Cyclist. — @davidhellmann.html">
<link rel="shortlink" href="http://wp.me/Pen6f-5">
<script type="text/javascript">var quoteCommentsSiteurl = "http://davidhellmann.com/wordpress";</script><script type="text/javascript" src="/js/mainPage/simple-comment-quotes.js"></script><style type="text/css">img#wpstats{display:none}</style>
<!-- Jetpack Open Graph Tags -->
<meta property="og:type" content="website">
<meta property="og:title" content="David Hellmann — Designer. Developer. Cyclist. — @davidhellmann">
<meta property="og:description" content="This is the portfolio, blog and digital playground from David Hellmann.">
<meta property="og:url" content="http://davidhellmann.com/">
<meta property="og:site_name" content="David Hellmann — Designer. Developer. Cyclist. — @davidhellmann">
<meta property="og:image" content="http://davidhellmann.com/wordpress/wp-content/themes/flatman/assets/img/davidhellmann_og.jpg">
<meta name="twitter:site" content="@jetpack">
<meta name="twitter:card" content="summary">
</head>

<body id="top">
<!-- start: Loader -->
<div class="loadingWrapper" style="top: 100%; display: none; opacity: 0.9;">
  <div class="loading">
    <h2>David<br>Hellmann<br></h2>
    <h3>loading...</h3>
  </div>
</div>
<!-- start: websiteWrapper -->
<section class="websiteWrapper">

  <!-- start: pageHeader -->
  <header class="websiteHeader ">
    <nav class="websiteNav">
      <h1>
        <a href="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/David Hellmann — Designer. Developer. Cyclist. — @davidhellmann.html">David Hellmann</a>
      </h1>
      <ul class="prim">
        <li><a href="http://davidhellmann.com/work">Work</a></li>
        <li><a href="http://davidhellmann.com/blog">Blog</a></li>
        <li><a href="http://davidhellmann.com/about">About</a></li>
      </ul>
      <ul class="sec">
        <li><a href="mailto:davidhellmann.com@gmail.com" class="js_showContact"><i class="icon icon-bubbles"></i></a></li>
        <li><a href="http://davidhellmann.com/#--search" class="js_showSearch"><i class="icon icon-search"></i></a></li>
      </ul>
      <ul class="mobile">
        <li><a href="http://davidhellmann.com/#mobileNav" class="js_showMobileNav"><i class="icon icon-menu"></i></a></li>
      </ul>
    </nav>
  </header>

  <section class="searchBox js_searchBox">
  <form method="get" action="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/David Hellmann — Designer. Developer. Cyclist. — @davidhellmann.html">
    <i class="icon icon-search"></i>
    <a href="http://davidhellmann.com/#closeSearch" class="js_showSearch"><i class="icon icon-close"></i></a>
    <input placeholder="Search..." name="s" class="searchInput" id="s"><input type="submit" class="submit" value="Search">
  </form>
</section>

  <div class="mobileNavWrapper">
    <nav class="navi">
      <ul>
        <li><a href="http://davidhellmann.com/work">Work</a></li>
        <li><a href="http://davidhellmann.com/blog">Blog</a></li>
        <li><a href="http://davidhellmann.com/about">About</a></li>
        <li><a href="mailto:davidhellmann.com@gmail.com" class="js_showContact"><i class="icon icon-bubbles"></i></a></li>
        <li><a href="http://davidhellmann.com/#--search" class="js_showSearch js_hideMobileNav"><i class="icon icon-search"></i></a></li>
      </ul>
    </nav>
  </div>







  <section class="welcomeWrapper">
    <figure style="background-image: url(http://davidhellmann.com/wordpress/wp-content/themes/flatman/assets/img/img_home_davidhellmann.jpg);">
      <figcaption>
        <h2><span>Designer<br>Developer<br>Cyclist</span></h2>
        <h3>Bikes. Food. Vodka. Cocktails.<br>Tattoos. Girls in Sneakers. ...</h3>
      </figcaption>
    </figure>
    <a href="http://davidhellmann.com/#article" class="scrollDown" id="article">
      <i class="icon icon-arrow-bottom"></i>Read my Articles
    </a>
  </section>


  <section class="articleArchiv">
    <ul class="sameHeight">
          <li style="height: 474px;">
        <a href="http://davidhellmann.com/blogging/ray-ban-polarized-tour-2014-iampolarized-polarizedtour2014-2467/" rel="bookmark" title=" Ray-Ban Polarized Tour 2014 — #iampolarized  #polarizedtour2014">
          <span class="date">30, June 2014</span>
          <h2>Ray-Ban Polarized Tour 2014 — #iampolarized  #polarizedtour2014</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          <li style="height: 474px;">
        <a href="http://davidhellmann.com/blogging/css-media-queries-das-problem-mit-fixen-breakpoints-2433/" rel="bookmark" title=" CSS Media Queries: Das Problem mit fixen Breakpoints">
          <span class="date">19, May 2014</span>
          <h2>CSS Media Queries: Das Problem mit fixen Breakpoints</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          <li style="height: 474px;">
        <a href="http://davidhellmann.com/blogging/changecgn-minirampe-gegen-haessliches-koeln-2451/" rel="bookmark" title=" #changeCGN — Minirampe gegen hässliches Köln!">
          <span class="date">18, May 2014</span>
          <h2>#changeCGN —&nbsp;Minirampe gegen hässliches Köln!</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          <li style="height: 434px;">
        <a href="http://davidhellmann.com/blogging/dribbble-invites-zu-vergeben-2446/" rel="bookmark" title=" dribbble invites zu vergeben!">
          <span class="date">12, May 2014</span>
          <h2>dribbble invites zu vergeben!</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          <li style="height: 434px;">
        <a href="http://davidhellmann.com/blogging/awwwards-honorable-mention-2448/" rel="bookmark" title=" AWWWARDS — Honorable Mention">
          <span class="date">12, May 2014</span>
          <h2>AWWWARDS — Honorable Mention</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          <li style="height: 434px;">
        <a href="http://davidhellmann.com/empfehlungen/peak-vote-for-me-on-awwwards-2444/" rel="bookmark" title=" Peak! Vote for me on AWWWARDS">
          <span class="date">08, May 2014</span>
          <h2>Peak! Vote for me on AWWWARDS</h2>
          <div class="readMore">Read Article<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
            </ul>
    <a class="getMoreButton" href="http://davidhellmann.com/blog">More Articles</a>
  </section>

<section class="myWork" id="work">
  <a href="http://davidhellmann.com/#work" class="scrollDown">
    <i class="icon icon-arrow-bottom"></i>See my work
  </a>

  
    <section class="latestWorkWrapper">
    <div class="latestWork">
      <div class="ipad">
        <div class="homeButton"><span></span></div>
        <div class="camera"></div>
        <figure>
          <a class="link" href="http://davidhellmann.com/work/home-on-earth/" title="Home on Earth">
  		      <img class="preview" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/HomeOnEarth_01_desktop.jpg" alt="Home on Earth">
            <img class="helper" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/helper_trans_1024x768.png" alt="helper">
  		    </a>
        </figure>
      </div>
      <div class="content">
        <h2>Home on Earth</h2>
        <p>
          Mein erstes Projekt 2013 was ich hier online stelle. Hat sich spontan ergeben und hat viel Spaß gemacht das ganze. Mein Part war die Company Website und dort war ich verantwortlich für das Design sowie die Umsetzung. Die Seite sollte ein Gefühl rüber bringen was man im Shop (der ist auch ganz neu online!) zu kaufen bekommt. Es geht um Natur und schöne Dinge. Und sind wir doch mal ehrlich. Das mögen wir alle! Vielleicht findet der ein oder andere ja gefallen an der Seite und gibt auch mal ne Bestellung auf. Lohnt sich auf jeden Fall. Und jetzt los, schaut es euch an!        </p>
        <div class="colors">
                    	        		<span class="colorField" style="background: #ebae0c"></span>
          	        		<span class="colorField" style="background: #f2f2f2"></span>
          	        		<span class="colorField" style="background: #342514"></span>
          	        		<span class="colorField" style="background: #90a1ae"></span>
          	        		<span class="colorField" style="background: #ffffff"></span>
          	        		<span class="colorField" style="background: #333333"></span>
          	                  </div>

        <ul class="range">
          <li>Art Direction</li><li>Design</li><li>Frontend Development</li>        </ul>
        <a class="getMoreButton" href="http://davidhellmann.com/work/home-on-earth/" title="Home on Earth">View details</a>
      </div>
    </div>
  </section>
	
  <section class="moreWork">
    <ul class="sameHeight">
                   <li style="height: 502px;">
        <a href="http://davidhellmann.com/work/millhaus/">
          <h2>Millhaus</h2>
          <figure>
            <img class="preview" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/millhaus_01_image_01-480x1225.jpg" alt="Millhaus">
            <img class="helper" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/helper_trans_10x10.png" alt="helper">
          </figure>
          <div class="readMore">View details<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
                   <li style="height: 502px;">
        <a href="http://davidhellmann.com/work/makebetterwebsites/">
          <h2>Make Better Websites</h2>
          <figure>
            <img class="preview" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/makebetterwebsites_01_image_01-480x1605.jpg" alt="Make Better Websites">
            <img class="helper" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/helper_trans_10x10.png" alt="helper">
          </figure>
          <div class="readMore">View details<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
                   <li style="height: 502px;">
        <a href="http://davidhellmann.com/work/betterdoc/">
          <h2>BetterDoc</h2>
          <figure>
            <img class="preview" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/BetterDoc_01_image_01-480x1810.jpg" alt="BetterDoc">
            <img class="helper" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/helper_trans_10x10.png" alt="helper">
          </figure>
          <div class="readMore">View details<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
                   <li style="height: 502px;">
        <a href="http://davidhellmann.com/work/deutsches-obst-und-gemuese/">
          <h2>Deutsches Obst und Gemüse</h2>
          <figure>
            <img class="preview" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/doug_01_image_01-480x798.jpg" alt="Deutsches Obst und Gemüse">
            <img class="helper" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/helper_trans_10x10.png" alt="helper">
          </figure>
          <div class="readMore">View details<i class="icon icon-arrow-right"></i></div>
        </a>
      </li>
          </ul>
    <a class="getMoreButton" href="http://davidhellmann.com/work">See all my Work</a>
  </section>

</section>
  <footer class="websiteFooter">
    <section class="footerContent">
      <div class="shortInfo">
        © 2006-2014 David Hellmann<br>
        Run with <a href="http://wordpress.org/">WordPress</a> / Made on an <a href="http://www.apple.com/imac/">Apple Computer</a><br>
        Gehostet bei <a href="http://www.hosteurope.de/" title="hosted by Host Europe" target="_self" rel="nofollow">Host Europe</a>
      </div>
      <ul class="socialIcons">
        <li><a href="http://superb.li/"><i class="icon icon-tumblr"></i></a></li>
        <li><a href="https://dribbble.com/davidhellmann"><i class="icon icon-dribbble"></i></a></li>
        <li><a href="https://twitter.com/davidhellmann"><i class="icon icon-twitter"></i></a></li>
        <li><a href="http://instagram.com/davidhellmann"><i class="icon icon-instagram"></i></a></li>
      </ul>
    </section>
    <a class="imprint" href="http://davidhellmann.com/imprint">Imprint</a>
  </footer>
</section>

<!-- start: pageHeader Sticky -->
<header class="websiteHeaderSticky">
  <nav class="websiteNav">
    <h1>
      <a href="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/David Hellmann — Designer. Developer. Cyclist. — @davidhellmann.html">David Hellmann</a>
    </h1>
    <ul class="prim">
      <li><a href="http://davidhellmann.com/work">Work</a></li>
      <li><a href="http://davidhellmann.com/blog">Blog</a></li>
      <li><a href="http://davidhellmann.com/about">About</a></li>
    </ul>
    <ul class="sec">
      <li><a href="mailto:davidhellmann.com@gmail.com" class="js_showContact"><i class="icon icon-bubbles"></i></a></li>
      <li><a href="http://davidhellmann.com/#--search" class="js_showSearch"><i class="icon icon-search"></i></a></li>
    </ul>
    <ul class="mobile">
      <li><a href="http://davidhellmann.com/#mobileNav" class="js_showMobileNav"><i class="icon icon-menu"></i></a></li>
    </ul>
  </nav>
</header>

<script type="text/javascript" src="/js/mainPage/devicepx-jetpack.js"></script>

	<script src="js/mainPage/e-201430.js" type="text/javascript"></script>
	<script type="text/javascript">
	st_go({v:'ext',j:'1:3.0.1',blog:'3425391',post:'5',tz:'2'});
	var load_cmc = function(){linktracker_init(3425391,5,2);};
	if ( typeof addLoadEvent != 'undefined' ) addLoadEvent(load_cmc);
	else load_cmc();
	</script><img id="wpstats" src="./David Hellmann — Designer. Developer. Cyclist. — @davidhellmann_files/g.gif" alt="">
<script type="text/javascript" src="js/mainPage/scripts-ck.js"></script>




















































</body></html>