<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" style="overflow: hidden; height: 100%;">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	
		<title>J-TEST</title>
		<meta name="author" content="Jun Wang">
		<meta name="description" content="List of task need to be done.">
		<meta name="keywords" content="task">
		<meta name="Resource-type" content="Document">
	    <script src="/js/lib/jquery.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				console.log("document is ready");
			});
		</script>
		<style media="screen" type="text/css">
		html { 
		  background: url('/img/tasklist/road.jpg') no-repeat center center fixed; 
		  -webkit-background-size: cover;
		  -moz-background-size: cover;
		  -o-background-size: cover;
		  background-size: cover;
		}
		.resovled{color: gray;}
		</style>
	</head>
	<body>
		<div style="width: 70%; margin: auto; height: 800px; overflow: scroll; line-height: 100px; font-size: 30px;  font-weight: 500;font-family: 'MuseoSans_Fat'; color: rgba(255,255,255,0.75);">
			<ul>
				<li class='resovled'>
					1. Set up route for zend.
				</li>
				<li>
					2. Clean up unessary code in EC2.
				</li>
				<li>
					3. Set up DB(RDS) via AWS.
				</li>
				<li class='resovled'>
					4. Set up local DB connect.
				</li>
				<li class='resovled'>
					5. Set up app.ini.
				</li>
				<li>
					6. Install livereload on local.
				</li>
				<li>
					7. Grab user content from scial web site and genrate key words.
				</li>
				<li>
					8. Install imagick on local.
				</li>
				<li>
					9. Install imagick on EC2.
				</li>
				<li>
					10. Install imagick on EC2.
				</li>
				<li>
					11. CV page.
				</li>
				<li>
					12. Tools page.
				</li>
				<li>
					13. Install phantom.
				</li>
			</ul>
		</div>
		


	</body>
</html>